use_frameworks!

platform :ios, '10.0'

target 'MessagingInAppWrapper_Example' do
  pod 'MessagingInAppWrapper', :path => '../'

  target 'MessagingInAppWrapper_Tests' do
    inherit! :search_paths

    
  end
end
